updated commands

diff --git a/.config/mise/tasks/pulumi-refresh b/.config/mise/tasks/pulumi-refresh
--- a/.config/mise/tasks/pulumi-refresh
+++ b/.config/mise/tasks/pulumi-refresh
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-#MISE description="Update Pulumi stacks"
+#MISE description="Refresh Pulumi stacks"
 
 for dir in stacks/*/; do
   echo "Running in $(basename "$dir")..."
   pushd "stacks/$(basename "$dir")" > /dev/null || continue
-  mise exec -- npm run cancel && mise exec -- npm run up || echo "Failed in $dir"
+  mise exec -- npm run cancel && mise exec -- npm run refresh || echo "Failed in $dir"
   popd > /dev/null || continue
 done
